version: '3.0'
services:
  server:
    image: sgratzl/seq2seq-vis-base
    working_dir: '/ws'
    command: '"source activate s2sv && python3 server.py --dir /data"'
    volumes:
      - './data/0316-fakedates:/data'
      - '.:/ws'
    ports:
      - '8080:8080'
